{
 "title": "Store",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Used Memory (Pools)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"store\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Ratio of CPU Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{instance=\"store\"}[1m])) / sum(rate(process_cpu_seconds_total[1m])) * 100"
    }
   ]
  },
  {
   "title": "Avg GC Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{instance=\"store\"}[1m])) by (gc) / sum(rate(jvm_gc_collection_seconds_count[1m])) by (gc)",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Number of Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jvm_threads_current{instance=\"store\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(jvm_threads_current{instance=\"store\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "min(jvm_threads_current{instance=\"store\"})",
     "legendFormat": "min"
    }
   ]
  }
 ]
}